### ISSUE TITLE
Sketch a Logo for tnbCrow - Bounty

### ISSUE THREAD

**Issue by dhakal0kushal** [tnbCrow/Design#13]
#### Task
Create a logo sketch for **tnbCrow**. Know more about the project [here](https://github.com/tnbCrow/Backend/blob/main/about.md).

#### Requirement:
Sketch a logo that revolves around the concept of **tnbCrow**, an escrow application being built for thenewboston. OR Sketch a logo that we cannot stop using.

#### Rules:
- One GitHub account can claim the bounty once. 
- The best three logos, that will choose, will be eligible for the bounty.

#### How to submit?
Comment this issue with your sketch.

#### Reward
- The sketch that we decide to use as a logo will get the bounty of **500** coins.
- Other two sketches, that were appealing enough, will get **100** coins each. Note: More or fewer sketches could get this bounty.

#### Have a question?
Comment your question.

#### Deadline: 1st April 2021

**Comment by denistsoi** [comment]
![sketches](https://cdn.discordapp.com/attachments/819968712823013416/824304935238893608/denis-tnbcrow.png)

- updated finals today/tomorrow

**Comment by denistsoi** [comment]
![Uploading image0.jpeg…]()

**Comment by Toledit** [comment]
Made to variation of the logo. One wich is more abstract than the other. Both designs are able to represent the brand and creatively incorporate thenewboston theme.
Also I have attached below more variations for the Logos.   Suggestions are welcome.

**Comment by denistsoi** [comment]
Remixing @Toledit's work

<img width="390" alt="Screenshot 2021-03-30 at 10 33 15 PM" src="https://user-images.githubusercontent.com/3061779/113007098-7ea1d380-91a8-11eb-96fa-2f16cbb089d2.png">
